import {client,imageUrl,projectsQuery,settingsQuery,sanityConfigured} from './sanity.js'
const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const projectsRoot=document.querySelector('.projects');
const aboutSection=document.querySelector('#about'),workSection=document.querySelector('#work');if(aboutSection&&workSection)workSection.before(aboutSection);
let allProjects=[],visibleProjects=6;
const normalizeMedia=m=>(m||[]).map(x=>x._type==='image'?{type:'image',src:imageUrl(x.asset),alt:x.alt||''}:{type:(x.mime||'').startsWith('video/')?'video':'file',src:x.src,alt:x.alt||''});
async function loadProjects(){if(!sanityConfigured)return;try{const projects=(await client.fetch(projectsQuery)).map(p=>({...p,media:normalizeMedia(p.media)}));if(projects.length){allProjects=projects;renderProjects()}else document.querySelector('.more-work')?.classList.add('hidden');const settings=await client.fetch(settingsQuery);if(settings?.resumeUrl){const link=document.querySelector('#resumeLink');link.href=settings.resumeUrl;link.download=settings.resumeName||'Linoy-Stephen-Resume'}}catch(e){console.warn('Sanity content unavailable; showing local portfolio content.',e)}}
function renderProjects(){const projects=allProjects.slice(0,visibleProjects);projectsRoot.innerHTML=projects.map((p,i)=>{const image=p.media?.find(m=>m.type==='image');return `<article class="project ${p.featured?'project-wide':''}" data-project="${esc(p.id)}"><div class="project-copy"><b>${String(i+1).padStart(2,'0')}</b><h3>${esc(p.title)}</h3><p>${esc(p.summary)}</p><span>${esc((p.services||[]).join?.(' · ')||p.services||p.category)}</span><button class="project-open">View project →</button></div><div class="media">${image?`<img src="${esc(image.src)}" alt="${esc(image.alt)}">`:''}</div></article>`}).join('');projectsRoot.querySelectorAll('[data-project]').forEach((el,i)=>el.querySelector('.project-open').onclick=()=>openProject(projects[i]));const more=document.querySelector('#loadMoreProjects'),count=document.querySelector('#projectCount');if(count)count.textContent=`Showing ${projects.length} of ${allProjects.length}`;if(more)more.hidden=projects.length>=allProjects.length}
document.querySelector('#loadMoreProjects')?.addEventListener('click',()=>{visibleProjects+=6;renderProjects()});
function videoEmbed(url){if(!url)return'';let src=url;if(/youtu\.be|youtube\.com/.test(url)){const id=url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{6,})/)?.[1];if(id)src=`https://www.youtube.com/embed/${id}`}else if(/vimeo\.com/.test(url)){const id=url.match(/vimeo\.com\/(\d+)/)?.[1];if(id)src=`https://player.vimeo.com/video/${id}`}return `<iframe src="${esc(src)}" title="Project video" allow="autoplay; fullscreen" allowfullscreen></iframe>`}
function openProject(p){let modal=document.querySelector('#projectModal');if(!modal){modal=document.createElement('dialog');modal.id='projectModal';document.body.appendChild(modal)}const gallery=(p.media||[]).map(m=>m.type==='video'?`<video controls src="${esc(m.src)}"></video>`:m.type==='image'?`<img src="${esc(m.src)}" alt="${esc(m.alt)}">`:'').join('');const services=(p.services||[]).join?.(', ')||p.services||'';modal.innerHTML=`<button class="modal-close" aria-label="Close">×</button><header><span>${esc(p.category)} · ${esc(p.year)}</span><h2>${esc(p.title)}</h2><p>${esc(p.summary)}</p></header><div class="case-meta"><div><b>Client</b><span>${esc(p.client||'Selected project')}</span></div><div><b>Services</b><span>${esc(services)}</span></div>${p.websiteUrl?`<a href="${esc(p.websiteUrl)}" target="_blank" rel="noopener">Visit website ↗</a>`:''}</div><div class="case-copy"><p>${esc(p.description)}</p></div><div class="case-gallery">${gallery}${videoEmbed(p.videoUrl)}</div>`;modal.querySelector('.modal-close').onclick=()=>modal.close();modal.showModal()}
loadProjects();
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
